#!/usr/bin/env bash

#setup git
git config --global user.email "anton.feldmann@gmail.com"
git config --global user.name "anton feldmann"


# switch branches and pull the data we want
echo "************************** get branch"
git checkout --orphan gh-pages
ls -la.
git fetch
echo "*************************** delete all"
rm -rf *
ls -la .
touch .nojekyll
echo "*************************** checkout master"
git checkout master docs/
ls -la .
# build the docs
echo "******************************* build doc"
cd docs
make clean
make html
cd ..
echo "***************************** mode doc"
mv ./docs/build/html/* .
git add -A
git commit -m "publishing updated docs..."
git push origin gh-pages

# switch back
#git checkout master