#!/usr/bin/env bash

# build the docs
echo "build doc"
cd docs
make clean
make html
cd ..

#setup git
git config --global user.email "anton.feldmann@gmail.com"
git config --global user.name "anton feldmann"

# commit and push
echo "push to master"
git add -A
git commit -m "building and pushing docs"
git push origin master

# switch branches and pull the data we want
echo "get branch"
git checkout --orphan gh-pages
git fetch
echo "delete all"
rm -rf .
touch .nojekyll
git checkout master docs/build/html
mv ./docs/build/html/* /docs
git add -A
git commit -m "publishing updated docs..."
git push origin gh-pages

# switch back
#git checkout master